document.write('<h1Welcome To GLA University')
document.write('<br>')
document.write('<hr>')
document.write('<h2>Branches in GLA</h2>')
document.write('<br>')
document.write('<h2>CSE</h2>')
document.write('<br>')
document.write('<h2>Mechanical</h2>')
document.write('<br>')
document.write('<h2>Electrical</h2>')
document.write('<br>')